# Generated by Django 4.2.9 on 2024-01-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('location', '0004_remove_location_companyautokey_and_more'),
        ('branch', '0004_remove_branch_registrationnum_branch_registorno_and_more'),
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PODTL',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(db_column='Seq')),
                ('indent', models.SmallIntegerField(db_column='Indent', null=True)),
                ('fontstyle', models.CharField(db_column='FontStyle', max_length=8, null=True)),
                ('mainitem', models.CharField(db_column='Mainitem', max_length=5)),
                ('numbering', models.CharField(db_column='Numbering', max_length=6, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('furtherdescription', models.CharField(db_column='FurtherDescription', max_length=255, null=True)),
                ('projno', models.CharField(db_column='ProjNo', max_length=10, null=True)),
                ('deptno', models.CharField(db_column='DeptNo', max_length=10, null=True)),
                ('uom', models.CharField(db_column='UOM', max_length=8, null=True)),
                ('useruom', models.CharField(db_column='UserUOM', max_length=8, null=True)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=8, max_digits=25, null=True)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=8, max_digits=25, null=True)),
                ('smallestqty', models.DecimalField(db_column='SmallestQty', decimal_places=8, max_digits=25, null=True)),
                ('transferedqty', models.DecimalField(db_column='TransferedQty', decimal_places=8, max_digits=25)),
                ('focqty', models.DecimalField(db_column='FOCQty', decimal_places=8, max_digits=25, null=True)),
                ('foctransferedqty', models.DecimalField(db_column='FOCTransferedQty', decimal_places=8, max_digits=25, null=True)),
                ('smallestunitprice', models.DecimalField(db_column='SmallestUnitPrice', decimal_places=8, max_digits=25, null=True)),
                ('unitprice', models.DecimalField(db_column='UnitPrice', decimal_places=8, max_digits=25, null=True)),
                ('discount', models.CharField(db_column='Discount', max_length=20, null=True)),
                ('discountamt', models.DecimalField(db_column='DiscountAmt', decimal_places=2, max_digits=19, null=True)),
                ('taxtype', models.CharField(db_column='TaxType', max_length=14, null=True)),
                ('tax', models.DecimalField(db_column='Tax', decimal_places=2, max_digits=19, null=True)),
                ('subtotal', models.DecimalField(db_column='SubTotal', decimal_places=2, max_digits=19, null=True)),
                ('localsubtotal', models.DecimalField(db_column='LocalSubTotal', decimal_places=2, max_digits=19, null=True)),
                ('transferable', models.CharField(db_column='Transferable', max_length=5)),
                ('printout', models.CharField(db_column='PrintOut', max_length=5)),
                ('dtltype', models.CharField(db_column='DTLType', max_length=5, null=True)),
                ('calcbypercent', models.DecimalField(db_column='CalcByPercent', decimal_places=6, max_digits=18, null=True)),
                ('addtosubtotal', models.CharField(db_column='AddToSubTotal', max_length=5)),
                ('fromdoctype', models.CharField(db_column='FromDocType', max_length=2, null=True)),
                ('fromdocno', models.CharField(db_column='FromDocNo', max_length=255, null=True)),
                ('fromdocdtlkey', models.BigIntegerField(db_column='FromDocDtlKey', null=True)),
                ('fulltransferoption', models.CharField(db_column='FullTransferOption', max_length=1, null=True)),
                ('fulltransferfromdoclist', models.CharField(db_column='FullTransferFromDocList', max_length=255, null=True)),
                ('fromsodtlkey', models.BigIntegerField(db_column='FromSODtl', null=True)),
                ('edtimateddeliverydate', models.CharField(db_column='EstimatedDeliveryDate', max_length=20, null=True)),
                ('fromaodtlkey', models.BigIntegerField(db_column='FromAODtlKey', null=True)),
                ('packagedockey', models.BigIntegerField(db_column='PackageDocKey', null=True)),
                ('parentdtlkey', models.BigIntegerField(db_column='ParentDtlKey', null=True)),
                ('subqty', models.DecimalField(db_column='SubQty', decimal_places=8, max_digits=25, null=True)),
                ('subtotalextax', models.DecimalField(db_column='SubTotalExTax', decimal_places=2, max_digits=19, null=True)),
                ('localtax', models.DecimalField(db_column='LocalTax', decimal_places=2, max_digits=19, null=True)),
                ('batchno', models.CharField(db_column='BatchNo', max_length=20, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('fromsodoclist', models.CharField(db_column='FromSODocList', max_length=255, null=True)),
                ('deliverydate', models.DateTimeField(db_column='DeliveryDate', null=True)),
                ('taxableamt', models.DecimalField(db_column='TaxableAmt', decimal_places=2, max_digits=19, null=True)),
                ('taxadjustment', models.DecimalField(db_column='TaxAdjustment', decimal_places=2, max_digits=19, null=True)),
                ('localsubtotalextax', models.DecimalField(db_column='LocalSubTotalExTax', decimal_places=2, max_digits=19, null=True)),
                ('extradiscountamt', models.DecimalField(db_column='ExtraDiscountAmt', decimal_places=2, max_digits=19, null=True)),
                ('taxrate', models.DecimalField(db_column='TaxRate', decimal_places=6, max_digits=18, null=True)),
                ('localtaxadjustment', models.DecimalField(db_column='LocalTaxAdjustment', decimal_places=2, max_digits=19, null=True)),
                ('localtaxableamt', models.DecimalField(db_column='LocalTaxableAmt', decimal_places=2, max_digits=19, null=True)),
                ('taxcurrencytax', models.DecimalField(db_column='TaxCurrencyTax', decimal_places=2, max_digits=19, null=True)),
                ('taxcurrencytaxableamt', models.DecimalField(db_column='TaxCurrencyTaxableAmt', decimal_places=2, max_digits=19, null=True)),
                ('salesexamtionno', models.CharField(db_column='SalesExamtionNo', max_length=60, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=100, null=True)),
                ('branchautokey', models.ForeignKey(db_column='BranchAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLBranchAutokey', to='branch.branch')),
                ('itemcode', models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLItemCodeAutokey', to='item.item')),
                ('location', models.ForeignKey(db_column='Location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLPOAutokey', to='location.location')),
                ('poautokey', models.ForeignKey(db_column='POAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLPOAutokey', to='po.po')),
            ],
            options={
                'db_table': 'PODTL',
                'ordering': ('autokey',),
                'managed': True,
            },
        ),
    ]
