# Generated by Django 4.2.9 on 2024-01-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podtl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podtl',
            name='branchautokey',
        ),
    ]
