# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('location', '0004_remove_location_companyautokey_and_more'),
        ('podtl', '0002_remove_podtl_branchautokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podtl',
            name='addtosubtotal',
            field=models.CharField(db_column='AddToSubTotal', max_length=1),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='dtltype',
            field=models.CharField(db_column='DTLType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLItemCodeAutokey', to='item.item'),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='location',
            field=models.ForeignKey(db_column='Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PODTLPOAutokey', to='location.location'),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='mainitem',
            field=models.CharField(db_column='Mainitem', max_length=1),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='printout',
            field=models.CharField(db_column='PrintOut', max_length=1),
        ),
        migrations.AlterField(
            model_name='podtl',
            name='transferable',
            field=models.CharField(db_column='Transferable', max_length=1),
        ),
    ]
