# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podtl', '0004_alter_podtl_autokey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='podtl',
            table='podtl',
        ),
    ]
