# Generated by Django 4.2.17 on 2024-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRate',
            fields=[
                ('crewrateguid', models.CharField(db_column='CrewRateGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('crewname', models.CharField(db_column='CrewName', max_length=88, null=True)),
                ('isactive', models.CharField(db_column='IsActive', max_length=1)),
            ],
            options={
                'db_table': 'crewrate',
                'ordering': ('crewrateguid',),
                'managed': True,
            },
        ),
    ]
