# Generated by Django 4.2.17 on 2024-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewrate',
            name='crewid',
            field=models.CharField(db_column='CrewId', default='NA', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
