# Generated by Django 4.2.9 on 2024-01-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='markupratio',
            field=models.DecimalField(db_column='MarkupRatio', decimal_places=6, max_digits=18, null=True),
        ),
    ]
