# Generated by Django 4.2.9 on 2024-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0002_alter_itemclass_markupratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='note',
            field=models.CharField(db_column='Note', max_length=255, null=True),
        ),
    ]
