# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0003_alter_itemclass_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemclass',
            table='itemclass',
        ),
    ]
