# Generated by Django 4.2.17 on 2024-12-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0004_alter_itemclass_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemclass',
            name='autokey',
        ),
        migrations.AddField(
            model_name='itemclass',
            name='itemclassguid',
            field=models.CharField(db_column='ItemClassGuid', default='NA', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
