# Generated by Django 4.2.17 on 2025-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0005_remove_itemclass_autokey_itemclass_itemclassguid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemclass',
            name='itemclass',
            field=models.CharField(db_column='ItemClass', max_length=20, unique=True),
        ),
    ]
