# Generated by Django 5.0.1 on 2024-01-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_address_alter_company_autokey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='Location', max_length=8)),
                ('description', models.CharField(db_column='Description', max_length=80, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=80, null=True)),
                ('address1', models.CharField(db_column='Address1', max_length=40, null=True)),
                ('address2', models.CharField(db_column='Address2', max_length=40, null=True)),
                ('address3', models.CharField(db_column='Address3', max_length=40, null=True)),
                ('address4', models.CharField(db_column='Address4', max_length=40, null=True)),
                ('postcode', models.CharField(db_column='PostCode', max_length=10, null=True)),
                ('phone1', models.CharField(db_column='Phone1', max_length=25, null=True)),
                ('phone2', models.CharField(db_column='Phone2', max_length=25, null=True)),
                ('fax1', models.CharField(db_column='Fax1', max_length=25, null=True)),
                ('fax2', models.CharField(db_column='Fax2', max_length=25, null=True)),
                ('contact', models.CharField(db_column='Contact', max_length=40, null=True)),
                ('note', models.CharField(db_column='Note', max_length=255, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', verbose_name=1)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('areacode', models.CharField(db_column='AreaCode', max_length=12, null=True)),
                ('cashpaymentmethod', models.CharField(db_column='CashPayment', max_length=20, null=True)),
                ('debitcardpayment', models.CharField(db_column='DebitCardPayment', max_length=20, null=True)),
                ('voucherpaymentmethod', models.CharField(db_column='VoucherPaymentMethod', max_length=20, null=True)),
                ('chequepaymentmethod', models.CharField(db_column='ChequePaymentMethod', max_length=20, null=True)),
                ('pointpaymentmethod', models.CharField(db_column='PointPaymentMethod', max_length=20, null=True)),
                ('roundingaccno', models.CharField(db_column='RoundingAccNo', max_length=12, null=True)),
                ('depositaccno', models.CharField(db_column='DepositAccNo', max_length=12, null=True)),
                ('forfeitedaccno', models.CharField(db_column='ForfeitedAccNo', max_length=12, null=True)),
                ('creditcardchargesaccno', models.CharField(db_column='CreditCardChargesAccNo', max_length=12, null=True)),
                ('pointpaymentaccno', models.CharField(db_column='PointPaymentAccNo', max_length=12, null=True)),
                ('servicechargeaccno', models.CharField(db_column='ServiceChargeAccNo', max_length=12, null=True)),
                ('voucherforfitedaccno', models.CharField(db_column='VoucherForfeitedAccNo', max_length=12, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=50, unique=True)),
                ('tipaccno', models.CharField(db_column='TipAccNo', max_length=12, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='LocationCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'Location',
                'ordering': ('location',),
                'managed': True,
            },
        ),
    ]
