# Generated by Django 4.2.9 on 2024-01-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='autokey',
            field=models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
