# Generated by Django 4.2.9 on 2024-01-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_autokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='isactive',
            field=models.CharField(db_column='IsActive', max_length=5),
        ),
    ]
