# Generated by Django 4.2.9 on 2024-01-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_remove_branch_registrationnum_branch_registorno_and_more'),
        ('location', '0003_alter_location_guid_alter_location_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='companyautokey',
        ),
        migrations.AddField(
            model_name='location',
            name='branchautokey',
            field=models.ForeignKey(db_column='BranchAutoKey', default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LocationBranchAutokey', to='branch.branch'),
            preserve_default=False,
        ),
    ]
