# Generated by Django 4.2.9 on 2024-02-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_companyautokey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(db_column='Location', max_length=8, unique=True),
        ),
    ]
