# Generated by Django 4.2.9 on 2024-03-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(db_column='Location', max_length=30, unique=True),
        ),
    ]
