# Generated by Django 4.2.9 on 2024-03-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32, null=True, unique=True),
        ),
    ]
