# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_location_guid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='location',
        ),
    ]
