# Generated by Django 4.2.17 on 2024-12-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissionitemclass', '0001_initial'),
        ('crewrate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRateDtl',
            fields=[
                ('crewratedtlguid', models.CharField(db_column='CrewRateDtlGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('crewtype', models.CharField(db_column='CrewType', max_length=50, null=True)),
                ('commvalue', models.DecimalField(db_column='UnitCost', decimal_places=4, max_digits=25, null=True)),
                ('commissionitemclassguid', models.ForeignKey(db_column='CommissionItemClassGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CrewRateDtlCommissionItemClassGuid', to='commissionitemclass.commissionitemclass')),
                ('crewrateguid', models.ForeignKey(db_column='CrewRateGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CrewRateDtlCrewRateGuid', to='crewrate.crewrate')),
            ],
            options={
                'db_table': 'crewratedtl',
                'ordering': ('crewratedtlguid',),
                'managed': True,
            },
        ),
    ]
