# Generated by Django 4.2.17 on 2024-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewratedtl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewratedtl',
            name='commvalue',
            field=models.DecimalField(db_column='CommValue', decimal_places=4, max_digits=5, null=True),
        ),
    ]
