# Generated by Django 4.2.17 on 2025-01-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewratedtl', '0002_alter_crewratedtl_commvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewratedtl',
            name='commvalue',
            field=models.DecimalField(db_column='CommValue', decimal_places=7, max_digits=8, null=True),
        ),
    ]
