# Generated by Django 4.2.14 on 2024-07-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0002_alter_gr_createdtimestamp'),
        ('grdtl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grdtl',
            old_name='grautokey',
            new_name='headerautokey'
        )
        # migrations.RemoveField(
        #     model_name='grdtl',
        #     name='grautokey',
        # ),
        # migrations.AddField(
        #     model_name='grdtl',
        #     name='headerautokey',
        #     field=models.ForeignKey(db_column='HeaderAutoKey', default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRDTLGRAutokey', to='gr.gr'),
        #     preserve_default=False,
        # ),
    ]
