# Generated by Django 4.2.16 on 2024-10-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0002_alter_gr_createdtimestamp'),
        ('grdtl', '0002_remove_grdtl_grautokey_grdtl_headerautokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grdtl',
            name='headerautokey',
            field=models.ForeignKey(db_column='HeaderAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='GRDTLGRAutokey', to='gr.gr'),
        ),
    ]
