# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grdtl', '0003_alter_grdtl_headerautokey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='grdtl',
            table='grdtl',
        ),
    ]
