# Generated by Django 4.2.9 on 2024-01-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='allowexceedcreditlimit',
            field=models.CharField(db_column='AllowExceedCreditLimit', max_length=1),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='exemptno',
            field=models.CharField(db_column='ExemptNo', max_length=60),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='gststatusverifieddate',
            field=models.DateTimeField(db_column='GSTStatusVerifiedDate', null=True),
        ),
    ]
