# Generated by Django 4.2.9 on 2024-01-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0002_alter_creditor_allowexceedcreditlimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='createdtimestamp',
            field=models.DateTimeField(auto_now=True, db_column='CreatedTimeStamp'),
        ),
    ]
