# Generated by Django 4.2.9 on 2024-02-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0003_alter_creditor_createdtimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='accno',
            field=models.CharField(db_column='AccNo', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='companyname',
            field=models.CharField(db_column='CompanyName', max_length=100, null=True, unique=True),
        ),
    ]
