# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0005_alter_creditor_displayterm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditor',
            table='creditor',
        ),
    ]
