# Generated by Django 4.2.9 on 2024-01-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemgroup', '0001_initial'),
        ('itemclass', '0002_alter_itemclass_markupratio'),
        ('taxtype', '0002_taxtype_taxtype'),
        ('itembrand', '0003_alter_itembrand_markupratio'),
        ('company', '0004_alter_company_autokey'),
        ('itemtype', '0001_initial'),
        ('creditor', '0001_initial'),
        ('itemcategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=30)),
                ('dockkey', models.IntegerField(db_column='DockKey')),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=100, null=True)),
                ('furtherdescription', models.CharField(db_column='FurtherDescription', max_length=255, null=True)),
                ('assemblycost', models.DecimalField(db_column='AssemblyCost', decimal_places=8, max_digits=25, null=True)),
                ('leadtime', models.CharField(db_column='LeadTime', max_length=40, null=True)),
                ('stockcontrol', models.CharField(db_column='StockControl', max_length=5)),
                ('hasserialno', models.CharField(db_column='HasSerialNo', max_length=5)),
                ('hasbatchno', models.CharField(db_column='HasBatchNo', max_length=5)),
                ('dutyrate', models.DecimalField(db_column='DutyRate', decimal_places=6, max_digits=18)),
                ('note', models.CharField(db_column='Note', max_length=255, null=True)),
                ('image', models.BinaryField(db_column='Image', null=True)),
                ('costingmethod', models.SmallIntegerField(db_column='CostingMethod')),
                ('salesuom', models.CharField(db_column='SalesUOM', max_length=8)),
                ('purchaseuom', models.CharField(db_column='PurchaseUOM', max_length=8)),
                ('reportuom', models.CharField(db_column='ReportUOM', max_length=8)),
                ('lastmodified', models.DateTimeField(db_column='LastModified')),
                ('lastmodifieduserid', models.CharField(db_column='LastModifiedUserID', max_length=10)),
                ('createdtimestamp', models.DateTimeField(auto_now=True, db_column='CreatedTimeStamp')),
                ('createduserid', models.CharField(db_column='CreatedUserID', max_length=10)),
                ('isactive', models.CharField(db_column='IsActive', max_length=5)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('snformatname', models.CharField(db_column='SNFormatName', max_length=5, null=True)),
                ('iscalcbonuspoint', models.CharField(db_column='IsCalcBonusPoint', max_length=5, null=True)),
                ('markupratio', models.DecimalField(db_column='MarkupRatio', decimal_places=6, max_digits=18, null=True)),
                ('haspromoter', models.CharField(db_column='HasPromoter', max_length=5)),
                ('globalcode', models.CharField(db_column='GlobalCode', max_length=30, null=True)),
                ('leadtimeday', models.IntegerField(db_column='LeadTimeDay', null=True)),
                ('externallink', models.CharField(db_column='ExternalLink', max_length=255, null=True)),
                ('discontinued', models.CharField(db_column='Discontinued', max_length=5)),
                ('autouomconversion', models.CharField(db_column='AutoUOMConversion', max_length=5, null=True)),
                ('baseuom', models.CharField(db_column='BaseUOM', max_length=8)),
                ('backordercontrol', models.CharField(db_column='BackOrderCOntrol', max_length=5)),
                ('purchasetaxtype', models.CharField(db_column='PurchaseTaxType', max_length=14, null=True)),
                ('tariffcode', models.CharField(db_column='TariffCode', max_length=12, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('issalesitem', models.CharField(db_column='IsSalesItem', max_length=5, null=True)),
                ('ispurchaseitem', models.CharField(db_column='IsPurchaseItem', max_length=5, null=True)),
                ('ispositem', models.CharField(db_column='IspOSItem', max_length=5, null=True)),
                ('israwmeterialitem', models.CharField(db_column='IsRawMaterialItem', max_length=5, null=True)),
                ('isfinishgoodsitem', models.CharField(db_column='IsFinishGoodsItem', max_length=5, null=True)),
                ('imagefilename', models.CharField(db_column='ImageFileName', max_length=120, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCompanyAutokey', to='company.company')),
                ('itembrand', models.ForeignKey(db_column='ItemBrand', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemBrandItemBrand', to='itembrand.itembrand')),
                ('itemcategory', models.ForeignKey(db_column='ItemCategory', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCategoryItemCategory', to='itemcategory.itemcategory')),
                ('itemclass', models.ForeignKey(db_column='ItemClass', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemClassItemClass', to='itemclass.itemclass')),
                ('itemgroup', models.ForeignKey(db_column='ItemGroup', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroupItemGroup', to='itemgroup.itemgroup')),
                ('itemtype', models.ForeignKey(db_column='ItemType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemTypeItemType', to='itemtype.itemtype')),
                ('mainsupplier', models.ForeignKey(db_column='MainSupplier', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CreditorAutoKey', to='creditor.creditor')),
                ('taxtype', models.ForeignKey(db_column='TaxType', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TaxTypeTaxType', to='taxtype.taxtype')),
            ],
            options={
                'db_table': 'Item',
                'ordering': ('itemcode',),
                'managed': True,
            },
        ),
    ]
