# Generated by Django 4.2.9 on 2024-01-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32),
        ),
    ]
