# Generated by Django 4.2.9 on 2024-02-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemcode',
            field=models.CharField(db_column='ItemCode', max_length=30, unique=True),
        ),
    ]
