# Generated by Django 4.2.9 on 2024-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32),
        ),
    ]
