# Generated by Django 4.2.9 on 2024-03-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itembrand',
            field=models.CharField(db_column='ItemBrand', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemcategory',
            field=models.CharField(db_column='ItemCategory', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemclass',
            field=models.CharField(db_column='ItemClass', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemgroup',
            field=models.CharField(db_column='ItemGroup', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.CharField(db_column='ItemType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='taxtype',
            field=models.CharField(db_column='TaxType', max_length=30, null=True),
        ),
    ]
