# Generated by Django 4.2.9 on 2024-03-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_itembrand_alter_item_itemcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mainsupplier',
            field=models.CharField(db_column='MainSupplier', max_length=30),
        ),
    ]
