# Generated by Django 4.2.17 on 2025-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_item_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemcode',
            field=models.CharField(db_column='ItemCode', db_index=True, max_length=30, unique=True),
        ),
    ]
