# Generated by Django 4.2.9 on 2024-07-02 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debtor", "0002_alter_debtor_accno_alter_debtor_companyname"),
        ("iv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iv",
            name="Debtorname",
        ),
        migrations.AlterField(
            model_name="iv",
            name="debtorcode",
            field=models.ForeignKey(
                db_column="DebtorCode",
                default=20210104,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="IVDebtorCode",
                to="debtor.debtor",
                to_field="accno",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iv",
            name="debtorname",
            field=models.ForeignKey(
                db_column="DebtorName",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="IVDebtorName",
                to="debtor.debtor",
                to_field="companyname",
            ),
            preserve_default=False,
        ),
    ]
