# Generated by Django 4.2.9 on 2024-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iv", "0002_remove_iv_debtorname_alter_iv_debtorcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iv",
            name="salesagent",
            field=models.CharField(db_column="SalesAgent", max_length=50, null=True),
        ),
    ]
