# Generated by Django 4.2.14 on 2024-07-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_address'),
        ('iv', '0003_alter_iv_salesagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv',
            name='branchautokey',
            field=models.ForeignKey(db_column='BranchAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='IVBranchAutokey', to='branch.branch', to_field='address'),
        ),
    ]
