# Generated by Django 4.2.14 on 2024-07-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0004_alter_iv_branchautokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv',
            name='debtorname',
            field=models.CharField(db_column='DebtorName', max_length=80),
        ),
    ]
