# Generated by Django 4.2.16 on 2024-11-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesagent', '0002_alter_salesagent_approveremailaddress_and_more'),
        ('iv', '0005_alter_iv_debtorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv',
            name='salesagent',
            field=models.ForeignKey(db_column='SalesAgent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='IVSalesAgent', to='salesagent.salesagent', to_field='salesagent'),
        ),
    ]
