# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0006_alter_iv_salesagent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='iv',
            table='iv',
        ),
    ]
