# Generated by Django 4.2.17 on 2025-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0007_alter_iv_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='iv',
            name='udf_book',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
