# Generated by Django 4.2.17 on 2025-01-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0008_iv_udf_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv',
            name='udf_book',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
