# Generated by Django 4.2.17 on 2025-01-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0010_alter_iv_udf_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iv',
            name='udf_book',
        ),
        migrations.AddField(
            model_name='iv',
            name='udfbook',
            field=models.PositiveSmallIntegerField(db_column='UdfBook', default='0'),
            preserve_default=False,
        ),
    ]
