# Generated by Django 4.2.17 on 2025-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iv', '0011_remove_iv_udf_book_iv_udfbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iv',
            name='udfbook',
            field=models.PositiveSmallIntegerField(blank=True, db_column='UdfBook', null=True),
        ),
    ]
