# Generated by Django 4.2.9 on 2024-01-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='calcdiscountonunitprice',
            field=models.CharField(db_column='CalcDiscountOnUnitPrice', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='cn',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='cn',
            name='debtorcode',
            field=models.CharField(db_column='DebtorCode', max_length=12),
        ),
        migrations.AlterField(
            model_name='cn',
            name='inclusivetax',
            field=models.CharField(db_column='InclusiveTax', max_length=1),
        ),
        migrations.AlterField(
            model_name='cn',
            name='posttogl',
            field=models.CharField(db_column='PostToGL', max_length=1),
        ),
        migrations.AlterField(
            model_name='cn',
            name='posttostock',
            field=models.CharField(db_column='PostToStock', max_length=1),
        ),
        migrations.AlterField(
            model_name='cn',
            name='roundadj',
            field=models.DecimalField(db_column='RoundAdj', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='yourpodate',
            field=models.DateTimeField(db_column='YourPODate', null=True),
        ),
        migrations.AlterField(
            model_name='cn',
            name='yourpono',
            field=models.CharField(db_column='YourPONo', max_length=25, null=True),
        ),
    ]
