# Generated by Django 4.2.9 on 2024-07-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("debtor", "0004_alter_debtor_accno"),
        ("cn", "0002_alter_cn_calcdiscountonunitprice_alter_cn_cancelled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cn",
            name="debtorcode",
            field=models.ForeignKey(
                db_column="DebtorCode",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="CNDebtorCode",
                to="debtor.debtor",
                to_field="accno",
            ),
        ),
        migrations.AlterField(
            model_name="cn",
            name="debtorname",
            field=models.ForeignKey(
                db_column="DebtorName",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="CNDebtorName",
                to="debtor.debtor",
                to_field="companyname",
            ),
        ),
    ]
