# Generated by Django 4.2.9 on 2024-07-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cn", "0003_alter_cn_debtorcode_alter_cn_debtorname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cn",
            name="docno",
            field=models.CharField(db_column="DocNo", max_length=255),
        ),
    ]
