# Generated by Django 4.2.14 on 2024-07-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0004_alter_cn_docno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='debtorname',
            field=models.CharField(db_column='DebtorName', max_length=80),
        ),
    ]
