# Generated by Django 4.2.16 on 2024-11-04 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesagent', '0002_alter_salesagent_approveremailaddress_and_more'),
        ('cn', '0005_alter_cn_debtorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cn',
            name='salesagent',
            field=models.ForeignKey(db_column='SalesAgent', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CNSalesAgent', to='salesagent.salesagent', to_field='salesagent'),
        ),
    ]
