# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0006_alter_cn_salesagent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cn',
            table='cn',
        ),
    ]
