# Generated by Django 4.2.17 on 2025-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn', '0007_alter_cn_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cn',
            name='udfbook',
            field=models.PositiveSmallIntegerField(blank=True, db_column='UdfBook', default=2, null=True),
        ),
    ]
