# Generated by Django 4.2.17 on 2025-01-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LorryPlate',
            fields=[
                ('lorryplateguid', models.CharField(db_column='LorryPlateGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('lorrynumber', models.CharField(db_column='LorryNumber', max_length=30, unique=True)),
                ('createdat', models.DateTimeField(db_column='CreatedAt')),
            ],
            options={
                'db_table': 'lorryplate',
                'ordering': ('lorryplateguid',),
                'managed': True,
            },
        ),
    ]
