# Generated by Django 4.2.9 on 2024-01-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adj', '0001_initial'),
        ('location', '0004_remove_location_companyautokey_and_more'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADJDTL',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('seq', models.IntegerField(db_column='Seq')),
                ('numbering', models.CharField(db_column='Numbering', max_length=6, null=True)),
                ('batchno', models.CharField(db_column='BatchNo', max_length=20, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('furtherdescription', models.CharField(db_column='FurtherDescription', max_length=255, null=True)),
                ('projno', models.CharField(db_column='ProjNo', max_length=10, null=True)),
                ('deptno', models.CharField(db_column='DeptNo', max_length=10, null=True)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=8, max_digits=25, null=True)),
                ('uom', models.CharField(db_column='UOM', max_length=8, null=True)),
                ('subtotal', models.DecimalField(db_column='SubTotal', decimal_places=2, max_digits=19, null=True)),
                ('printout', models.CharField(db_column='PrintOut', max_length=5)),
                ('serialnolist', models.CharField(db_column='SerialNoList', max_length=255, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=100, null=True)),
                ('adjautokey', models.ForeignKey(db_column='ADJAutokey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJDTLCNAutokey', to='adj.adj')),
                ('itemcode', models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJDTLItemCodeAutokey', to='item.item')),
                ('location', models.ForeignKey(db_column='Location', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJDTLLocationAutokey', to='location.location')),
            ],
            options={
                'db_table': 'ADJDTL',
                'ordering': ('autokey',),
                'managed': True,
            },
        ),
    ]
