# Generated by Django 4.2.9 on 2024-01-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('location', '0004_remove_location_companyautokey_and_more'),
        ('adjdtl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjdtl',
            name='unitcost',
            field=models.DecimalField(db_column='UnitCost', decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='adjdtl',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJDTLItemCodeAutokey', to='item.item'),
        ),
        migrations.AlterField(
            model_name='adjdtl',
            name='location',
            field=models.ForeignKey(db_column='Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJDTLLocationAutokey', to='location.location'),
        ),
    ]
