# Generated by Django 4.2.9 on 2024-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjdtl', '0002_adjdtl_unitcost_alter_adjdtl_itemcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjdtl',
            name='printout',
            field=models.CharField(db_column='PrintOut', max_length=1),
        ),
    ]
