# Generated by Django 4.2.9 on 2024-01-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_remove_location_companyautokey_and_more'),
        ('item', '0001_initial'),
        ('dndtl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndtl',
            name='addtosubtotal',
            field=models.CharField(db_column='AddToSubTotal', max_length=1),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='dtltype',
            field=models.CharField(db_column='DtlType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='focqty',
            field=models.DecimalField(db_column='FOCQty', decimal_places=8, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='iscalcbonuspoint',
            field=models.CharField(db_column='IsCalcBonusPoint', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DNDTLItemCodeAutokey', to='item.item'),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='location',
            field=models.ForeignKey(db_column='Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='DNDTLLocationAutokey', to='location.location'),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='mainitem',
            field=models.CharField(db_column='MainItem', max_length=1),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='printout',
            field=models.CharField(db_column='PrintOut', max_length=1),
        ),
        migrations.AlterField(
            model_name='dndtl',
            name='salesexemptionno',
            field=models.CharField(db_column='SalesExemptionNo', max_length=60, null=True),
        ),
    ]
