# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndtl', '0002_alter_dndtl_addtosubtotal_alter_dndtl_dtltype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dndtl',
            table='dndtl',
        ),
    ]
