# Generated by Django 4.2.16 on 2024-11-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('salesagent', models.CharField(db_column='SalesAgent', max_length=40, unique=True)),
                ('description', models.CharField(db_column='Description', max_length=40, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=80, null=True)),
                ('isactive', models.CharField(db_column='IsActive', max_length=1)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('signature', models.BinaryField(db_column='Signature', null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('emailaddress', models.CharField(db_column='EmailAddress', max_length=200)),
                ('approveremailaddress', models.CharField(db_column='ApproverEmailAddress', max_length=200)),
            ],
            options={
                'db_table': 'SalesAgent',
                'ordering': ('salesagent',),
                'managed': True,
            },
        ),
    ]
