# Generated by Django 4.2.16 on 2024-11-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesagent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesagent',
            name='approveremailaddress',
            field=models.CharField(db_column='ApproverEmailAddress', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='emailaddress',
            field=models.CharField(db_column='EmailAddress', max_length=200, null=True),
        ),
    ]
