# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesagent', '0002_alter_salesagent_approveremailaddress_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesagent',
            table='salesagent',
        ),
    ]
