# Generated by Django 4.2.9 on 2024-01-22 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0004_remove_branch_registrationnum_branch_registorno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADJ',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('docno', models.CharField(db_column='DocNo', max_length=20)),
                ('docdate', models.DateTimeField(db_column='DocDate')),
                ('description', models.CharField(db_column='Description', max_length=80, null=True)),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=19, null=True)),
                ('note', models.CharField(db_column='Note', max_length=255, null=True)),
                ('remark1', models.CharField(db_column='Remark1', max_length=40, null=True)),
                ('remark2', models.CharField(db_column='Remark2', max_length=40, null=True)),
                ('remark3', models.CharField(db_column='Remark3', max_length=40, null=True)),
                ('remark4', models.CharField(db_column='Remark4', max_length=40, null=True)),
                ('printcount', models.SmallIntegerField(db_column='PrintCount')),
                ('cancelled', models.CharField(db_column='Cancelled', max_length=5)),
                ('lastmodified', models.DateTimeField(db_column='LastModified')),
                ('lastmodifieduserid', models.CharField(db_column='LastModifiedUserID', max_length=10)),
                ('createdtimestamp', models.DateTimeField(db_column='CreatedTimeStamp')),
                ('createduserid', models.CharField(db_column='CreatedUserID', max_length=10)),
                ('externallink', models.CharField(db_column='ExternalLink', max_length=255, null=True)),
                ('refdocno', models.CharField(db_column='RefDockNo', max_length=20, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('cansync', models.CharField(db_column='CanSync', max_length=5)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('branchautokey', models.ForeignKey(db_column='BranchAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ADJBranchAutokey', to='branch.branch')),
            ],
            options={
                'db_table': 'ADJ',
                'ordering': ('docno',),
                'managed': True,
            },
        ),
    ]
