# Generated by Django 4.2.9 on 2024-01-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adj',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='adj',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='adj',
            name='refdocno',
            field=models.CharField(db_column='RefDocNo', max_length=20, null=True),
        ),
    ]
