# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adj', '0002_alter_adj_cancelled_alter_adj_cansync_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adj',
            table='adj',
        ),
    ]
