# Generated by Django 4.2.9 on 2024-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='so',
            name='calcdiscountonunitprice',
            field=models.CharField(db_column='CalcDiscountOnUnitPrice', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='so',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='so',
            name='cantransferbyvalue',
            field=models.CharField(db_column='CanTransferByValue', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='inclusivetax',
            field=models.CharField(db_column='InclusiveTax', max_length=1),
        ),
        migrations.AlterField(
            model_name='so',
            name='isroundadj',
            field=models.CharField(db_column='IsRoundAdj', max_length=1),
        ),
        migrations.AlterField(
            model_name='so',
            name='roundadj',
            field=models.DecimalField(db_column='RoundAdj', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='transferable',
            field=models.CharField(db_column='Transferable', max_length=1),
        ),
    ]
