# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0002_alter_so_calcdiscountonunitprice_alter_so_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='so',
            table='so',
        ),
    ]
