# Generated by Django 4.2.17 on 2024-12-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemclass', '0005_remove_itemclass_autokey_itemclass_itemclassguid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionItemClass',
            fields=[
                ('commissionitemclassguid', models.CharField(db_column='CommissionItemClassGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('commtype', models.CharField(db_column='CommType', max_length=20)),
                ('itemclassguid', models.ForeignKey(db_column='ItemClassGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CommissionItemClassItemClassGuid', to='itemclass.itemclass')),
            ],
            options={
                'db_table': 'commissionitemclass',
                'ordering': ('commissionitemclassguid',),
                'managed': True,
            },
        ),
    ]
