# Generated by Django 4.2.9 on 2024-01-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(db_column='Description', max_length=40, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=40, null=True)),
                ('note', models.CharField(db_column='Note', max_length=255, null=True)),
                ('salescode', models.CharField(db_column='SalesCode', max_length=12, null=True)),
                ('cashsalescode', models.CharField(db_column='CashSalesCode', max_length=12, null=True)),
                ('salesreturncode', models.CharField(db_column='SalesReturnCode', max_length=12, null=True)),
                ('salesdiscountcode', models.CharField(db_column='SalesDiscountCode', max_length=12, null=True)),
                ('purchasecode', models.CharField(db_column='PurchaseCode', max_length=12, null=True)),
                ('purchasereturncode', models.CharField(db_column='PurchaseReturnCode', max_length=12, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('shortcode', models.CharField(db_column='ShortCode', max_length=8, null=True)),
                ('markupratio', models.DecimalField(db_column='MarkupRation', decimal_places=6, max_digits=18, null=True)),
                ('balancestockcode', models.CharField(db_column='BalanceStockCode', max_length=12, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('roundingmethod', models.CharField(db_column='RoundingMethod', max_length=10, null=True)),
                ('roundingamount', models.CharField(db_column='RoundingAmount', max_length=10, null=True)),
                ('cashpurchasecode', models.CharField(db_column='CashPurchaseCode', max_length=12, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemGroupCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'ItemGroup',
                'ordering': ('autokey',),
                'managed': True,
            },
        ),
    ]
