# Generated by Django 4.2.9 on 2024-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='autokey',
            field=models.CharField(db_column='AutoKey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
