# Generated by Django 4.2.17 on 2024-12-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionguid', models.CharField(db_column='TransactionGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('docno', models.CharField(db_column='DocNo', max_length=20)),
                ('docdate', models.DateTimeField(db_column='DocDate')),
                ('debtorname', models.CharField(db_column='DebtorName', max_length=80)),
                ('debtorcode', models.CharField(db_column='DebtorCode', max_length=80)),
                ('lorryguid', models.ForeignKey(db_column='LorryGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransactionLorryGuid', to='lorry.lorry')),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ('transactionguid',),
                'managed': True,
            },
        ),
    ]
