# Generated by Django 4.2.17 on 2025-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='udfispallet',
            field=models.SmallIntegerField(blank=True, db_column='UdfIsPallet', default=0, null=True),
        ),
    ]
