# Generated by Django 4.2.17 on 2024-12-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crewguid', models.CharField(db_column='CrewGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('crewname', models.CharField(db_column='CrewName', max_length=88, null=True)),
                ('crewtype', models.CharField(db_column='CrewType', max_length=55, null=True)),
                ('lorryguid', models.ForeignKey(db_column='LorryGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CrewLorryGuid', to='lorry.lorry')),
            ],
            options={
                'db_table': 'crew',
                'ordering': ('crewguid',),
                'managed': True,
            },
        ),
    ]
