# Generated by Django 4.2.17 on 2025-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='crewid',
            field=models.CharField(db_column='CrewId', default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
