# Generated by Django 4.2.17 on 2025-01-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_crew_crewid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='crewname',
        ),
    ]
