# Generated by Django 4.2.9 on 2024-06-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0005_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Debtor",
            fields=[
                (
                    "autokey",
                    models.CharField(
                        db_column="Autokey",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("accno", models.CharField(db_column="AccNo", max_length=12)),
                (
                    "companyname",
                    models.CharField(
                        db_column="CompanyName", max_length=100, null=True
                    ),
                ),
                (
                    "desc2",
                    models.CharField(db_column="Desc2", max_length=100, null=True),
                ),
                (
                    "registorno",
                    models.CharField(db_column="RegistorNo", max_length=30, null=True),
                ),
                (
                    "address1",
                    models.CharField(db_column="Address1", max_length=40, null=True),
                ),
                (
                    "address2",
                    models.CharField(db_column="Address2", max_length=40, null=True),
                ),
                (
                    "address3",
                    models.CharField(db_column="Address3", max_length=40, null=True),
                ),
                (
                    "address4",
                    models.CharField(db_column="Address4", max_length=40, null=True),
                ),
                (
                    "postcode",
                    models.CharField(db_column="PostCode", max_length=10, null=True),
                ),
                (
                    "deliveraddr1",
                    models.CharField(
                        db_column="DeliverAddr1", max_length=40, null=True
                    ),
                ),
                (
                    "deliveraddr2",
                    models.CharField(
                        db_column="DeliverAddr2", max_length=40, null=True
                    ),
                ),
                (
                    "deliveraddr3",
                    models.CharField(
                        db_column="DeliverAddr3", max_length=40, null=True
                    ),
                ),
                (
                    "deliveraddr4",
                    models.CharField(
                        db_column="DeliverAddr4", max_length=40, null=True
                    ),
                ),
                (
                    "deliverpostcode",
                    models.CharField(
                        db_column="DeliverPostCode", max_length=10, null=True
                    ),
                ),
                (
                    "attention",
                    models.CharField(db_column="Attention", max_length=40, null=True),
                ),
                (
                    "phone1",
                    models.CharField(db_column="Phone1", max_length=25, null=True),
                ),
                (
                    "phone2",
                    models.CharField(db_column="Phone2", max_length=25, null=True),
                ),
                ("fax1", models.CharField(db_column="Fax1", max_length=25, null=True)),
                ("fax2", models.CharField(db_column="Fax2", max_length=25, null=True)),
                (
                    "areacode",
                    models.CharField(db_column="AreaCode", max_length=12, null=True),
                ),
                (
                    "salesagent",
                    models.CharField(db_column="SalesAgent", max_length=12, null=True),
                ),
                (
                    "debtortype",
                    models.CharField(db_column="DebtorType", max_length=20, null=True),
                ),
                (
                    "natureofbusiness",
                    models.CharField(
                        db_column="NatureOfBusiness", max_length=40, null=True
                    ),
                ),
                (
                    "weburl",
                    models.CharField(db_column="WebURL", max_length=80, null=True),
                ),
                (
                    "emailaddress",
                    models.CharField(
                        db_column="EmailAddress", max_length=200, null=True
                    ),
                ),
                (
                    "displayterm",
                    models.CharField(db_column="DisplayTerm", max_length=30),
                ),
                (
                    "creditlimit",
                    models.DecimalField(
                        db_column="CreditLimit",
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "agingon",
                    models.CharField(db_column="AgingOn", max_length=1, null=True),
                ),
                (
                    "statementtype",
                    models.CharField(
                        db_column="StatementType", max_length=1, null=True
                    ),
                ),
                (
                    "currencycode",
                    models.CharField(db_column="CurrencyCode", max_length=5),
                ),
                (
                    "allowexceedcreditlimit",
                    models.CharField(db_column="AllowExceedCreditLimit", max_length=5),
                ),
                ("note", models.CharField(db_column="Note", max_length=255, null=True)),
                (
                    "exemptno",
                    models.CharField(db_column="ExemptNo", max_length=60, null=True),
                ),
                ("expirydate", models.DateTimeField(db_column="ExpiryDate", null=True)),
                (
                    "pricecategory",
                    models.CharField(
                        db_column="PriceCategory", max_length=12, null=True
                    ),
                ),
                (
                    "taxtype",
                    models.CharField(db_column="TaxType", max_length=14, null=True),
                ),
                (
                    "discountpercent",
                    models.DecimalField(
                        db_column="DiscountPercent", decimal_places=6, max_digits=18
                    ),
                ),
                (
                    "detaildiscount",
                    models.CharField(
                        db_column="DetailDiscount", max_length=20, null=True
                    ),
                ),
                ("lastmodified", models.DateTimeField(db_column="LastModified")),
                (
                    "lastmodifieduserid",
                    models.CharField(db_column="LastModifiedUserID", max_length=10),
                ),
                (
                    "createduserid",
                    models.CharField(
                        db_column="CreatedUserID", editable=False, max_length=30
                    ),
                ),
                (
                    "overduelimit",
                    models.DecimalField(
                        db_column="OverdueLimit",
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "hasbonuspoint",
                    models.CharField(db_column="HasBonusPoint", max_length=1),
                ),
                (
                    "openingbonuspoint",
                    models.DecimalField(
                        db_column="OpeningBonuspoint",
                        decimal_places=2,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "otblockstatus",
                    models.SmallIntegerField(db_column="OTBlockStatus", null=True),
                ),
                (
                    "soblockstatus",
                    models.SmallIntegerField(db_column="SOBlockStatus", null=True),
                ),
                (
                    "doblockstatus",
                    models.SmallIntegerField(db_column="DOBlockStatus", null=True),
                ),
                (
                    "ivblockstatus",
                    models.SmallIntegerField(db_column="IVBlockStatus", null=True),
                ),
                (
                    "csblockstatus",
                    models.SmallIntegerField(db_column="CSBlockStatus", null=True),
                ),
                (
                    "qtblockmessage",
                    models.SmallIntegerField(db_column="QTBlockMessage", null=True),
                ),
                (
                    "soblockmessage",
                    models.SmallIntegerField(db_column="SOBlockMessage", null=True),
                ),
                (
                    "doblockmessage",
                    models.SmallIntegerField(db_column="DOBlockMessage", null=True),
                ),
                (
                    "ivblockmessage",
                    models.SmallIntegerField(db_column="IVBlockMessage", null=True),
                ),
                (
                    "csblockmessage",
                    models.SmallIntegerField(db_column="CSBlockMessage", null=True),
                ),
                (
                    "externallink",
                    models.CharField(
                        db_column="ExternalLink", max_length=255, null=True
                    ),
                ),
                (
                    "isgroupcompany",
                    models.CharField(db_column="IsGroupCompany", max_length=1),
                ),
                ("isactive", models.CharField(db_column="IsActive", max_length=1)),
                ("lastupdate", models.IntegerField(db_column="LastUpdate")),
                (
                    "contactinfo",
                    models.CharField(
                        db_column="ContactInfo", max_length=255, null=True
                    ),
                ),
                (
                    "accountgroup",
                    models.CharField(
                        db_column="AccountGroup", max_length=12, null=True
                    ),
                ),
                (
                    "markupratio",
                    models.DecimalField(
                        db_column="MarkupRatio",
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "taxregisterno",
                    models.CharField(
                        db_column="TaxRegisterNo", max_length=20, null=True
                    ),
                ),
                (
                    "calcdiscountonunitprice",
                    models.CharField(
                        db_column="CalcDiscountOnUnitPrice", max_length=1, null=True
                    ),
                ),
                (
                    "gststatusverifieddate",
                    models.DateTimeField(
                        db_column="GSTStatusVerifiedDate", editable=False, null=True
                    ),
                ),
                (
                    "inclusivetax",
                    models.CharField(db_column="InclusiveTax", max_length=1),
                ),
                ("roundingmethod", models.IntegerField(db_column="RoundingMethod")),
                (
                    "selfbilledapprovalno",
                    models.CharField(
                        db_column="SelfBilledApprovalNo", max_length=1, null=True
                    ),
                ),
                (
                    "guid",
                    models.CharField(db_column="Guid", max_length=32, unique=True),
                ),
                (
                    "istaxregistered",
                    models.CharField(
                        db_column="IsTaxRegistered", max_length=5, null=True
                    ),
                ),
                (
                    "receiptwithholdingtaxcode",
                    models.CharField(
                        db_column="ReceiptWithHoldingTaxCode", max_length=14, null=True
                    ),
                ),
                (
                    "paymentwithholdingtaxcode",
                    models.CharField(
                        db_column="PaymentWithHoldingTaxCode", max_length=14, null=True
                    ),
                ),
                (
                    "multiprice",
                    models.CharField(db_column="MultiPrice", max_length=8, null=True),
                ),
                (
                    "allowchangemultiprice",
                    models.CharField(
                        db_column="AllowChangeMultiPrice", max_length=1, null=True
                    ),
                ),
                (
                    "taxbranchid",
                    models.CharField(db_column="TaxBranchID", max_length=8, null=True),
                ),
                (
                    "servicetaxregisterno",
                    models.CharField(
                        db_column="ServiceTaxRegisterNo", max_length=20, null=True
                    ),
                ),
                (
                    "mobile",
                    models.CharField(db_column="Mobile", max_length=25, null=True),
                ),
                (
                    "cgblockstatus",
                    models.SmallIntegerField(db_column="CGBlockStatus", null=True),
                ),
                (
                    "cgblockmessage",
                    models.CharField(
                        db_column="CGBlockMessage", max_length=40, null=True
                    ),
                ),
                (
                    "companyautokey",
                    models.ForeignKey(
                        db_column="CompanyAutoKey",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="DebtorCompanyAutokey",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "db_table": "Debtor",
                "ordering": ("companyname",),
                "managed": True,
            },
        ),
    ]
