# Generated by Django 4.2.9 on 2024-07-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debtor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtor",
            name="accno",
            field=models.CharField(db_column="AccNo", max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="companyname",
            field=models.CharField(
                db_column="CompanyName", max_length=100, null=True, unique=True
            ),
        ),
    ]
