# Generated by Django 4.2.9 on 2024-07-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0007_alter_terms_displayterm"),
        ("debtor", "0002_alter_debtor_accno_alter_debtor_companyname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtor",
            name="displayterm",
            field=models.ForeignKey(
                db_column="DisplayTerm",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="DebtorDisplayTerm",
                to="terms.terms",
            ),
        ),
    ]
