# Generated by Django 4.2.9 on 2024-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("debtor", "0003_alter_debtor_displayterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtor",
            name="accno",
            field=models.CharField(db_column="AccNo", max_length=40, unique=True),
        ),
    ]
