# Generated by Django 4.2.14 on 2024-07-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0004_alter_debtor_accno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='companyname',
            field=models.CharField(db_column='CompanyName', max_length=100, null=True),
        ),
    ]
