# Generated by Django 4.2.17 on 2025-02-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtor', '0006_alter_debtor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='udfispallet',
            field=models.SmallIntegerField(blank=True, db_column='UdfIsPallet', default=0, null=True),
        ),
    ]
