# Generated by Django 4.2.9 on 2024-01-17 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBOM',
            fields=[
                ('autokey', models.CharField(db_column='AutoKey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=30)),
                ('subitemcode', models.CharField(db_column='SubItemCode', max_length=30)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=8, max_digits=25)),
                ('overheadcost', models.DecimalField(db_column='OverHeaseCost', decimal_places=8, max_digits=25)),
                ('seq', models.IntegerField(db_column='Seq')),
                ('costfraction', models.DecimalField(db_column='CostFraction', decimal_places=2, max_digits=19, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemBOMCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'ItemBOM',
                'ordering': ('itemcode',),
                'managed': True,
            },
        ),
    ]
