# Generated by Django 4.2.9 on 2024-01-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('itembom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembom',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemBOMItemCode', to='item.item'),
        ),
    ]
