# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembom', '0002_alter_itembom_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembom',
            name='overheadcost',
            field=models.DecimalField(db_column='OverHeadCost', decimal_places=8, max_digits=25),
        ),
    ]
