# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itembom', '0003_alter_itembom_overheadcost'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itembom',
            table='itembom',
        ),
    ]
