# Generated by Django 4.2.9 on 2024-01-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sodtl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sodtl',
            old_name='edtimateddeliverydate',
            new_name='estimateddeliverydate',
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='addtosubtotal',
            field=models.CharField(db_column='AddToSubTotal', max_length=1),
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='dtltype',
            field=models.CharField(db_column='DTLType', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='mainitem',
            field=models.CharField(db_column='Mainitem', max_length=1),
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='printout',
            field=models.CharField(db_column='PrintOut', max_length=1),
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='stockreceived',
            field=models.CharField(db_column='StockReceived', max_length=1),
        ),
        migrations.AlterField(
            model_name='sodtl',
            name='transferable',
            field=models.CharField(db_column='Transferable', max_length=1),
        ),
    ]
