# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sodtl', '0002_rename_edtimateddeliverydate_sodtl_estimateddeliverydate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sodtl',
            table='sodtl',
        ),
    ]
