# Generated by Django 4.2.9 on 2024-01-16 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(db_column='Description', max_length=120, null=True)),
                ('taxrate', models.DecimalField(db_column='TaxRate', decimal_places=6, max_digits=18)),
                ('inclusive', models.CharField(db_column='Inclusive', max_length=1)),
                ('isactive', models.CharField(db_column='IsActive', max_length=1)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('govtaxcode', models.CharField(db_column='GovTaxCode', max_length=8, null=True)),
                ('supplypurchase', models.CharField(db_column='SupplyPurchase', max_length=8)),
                ('isdefault', models.CharField(db_column='Isdefault', max_length=5)),
                ('taxaccno', models.CharField(db_column='TaxAccNo', max_length=12, null=True)),
                ('iszerorate', models.CharField(db_column='IsZeroRate', max_length=1)),
                ('usetrxtaxaccno', models.CharField(db_column='UseTrxTaxAccNo', max_length=1)),
                ('accountingbasis', models.IntegerField(db_column='AccountingBasis')),
                ('addtocost', models.CharField(db_column='AddToCost', max_length=1)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('taxsystem', models.CharField(db_column='TaxSystem', max_length=50, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TaxTypeCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'TaxType',
                'ordering': ('taxaccno',),
                'managed': True,
            },
        ),
    ]
