# Generated by Django 4.2.9 on 2024-01-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='taxtype',
            field=models.CharField(db_column='TaxType', default=1, max_length=14),
            preserve_default=False,
        ),
    ]
