# Generated by Django 4.2.9 on 2024-01-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxtype', '0002_taxtype_taxtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxtype',
            options={'managed': True, 'ordering': ('taxtype',)},
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='isdefault',
            field=models.CharField(db_column='Isdefault', max_length=1),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='supplypurchase',
            field=models.CharField(db_column='SupplyPurchase', max_length=1),
        ),
    ]
