# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxtype', '0003_alter_taxtype_options_alter_taxtype_isdefault_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taxtype',
            table='taxtype',
        ),
    ]
