# Generated by Django 5.0.1 on 2024-01-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_address_alter_company_autokey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('displayterm', models.CharField(db_column='DisplayTerm', max_length=30)),
                ('terms', models.CharField(db_column='Terms', max_length=30, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('termtype', models.CharField(db_column='Termtype', max_length=1, null=True)),
                ('termdays', models.IntegerField(db_column='TermDays', null=True)),
                ('discountdays', models.IntegerField(db_column='DiscountDays', null=True)),
                ('discountpercent', models.DecimalField(db_column='DiscountPercent', decimal_places=6, max_digits=18, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutokey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Company_autokey', to='company.company')),
            ],
            options={
                'db_table': 'Terms',
                'ordering': ('autokey',),
                'managed': True,
            },
        ),
    ]
