# Generated by Django 5.0.1 on 2024-01-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_address_alter_company_autokey_and_more'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='companyautokey',
            field=models.ForeignKey(db_column='CompanyAutokey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TermsCompanyAutoKey', to='company.company'),
        ),
    ]
