# Generated by Django 4.2.9 on 2024-02-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_alter_terms_companyautokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='displayterm',
            field=models.CharField(db_column='DisplayTerm', max_length=30, unique=True),
        ),
    ]
