# Generated by Django 4.2.9 on 2024-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0005_alter_terms_displayterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='termtype',
            field=models.CharField(db_column='Termtype', max_length=40, null=True),
        ),
    ]
