# Generated by Django 4.2.9 on 2024-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0006_alter_terms_termtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='displayterm',
            field=models.CharField(db_column='DisplayTerm', max_length=50, unique=True),
        ),
    ]
