# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0007_alter_terms_displayterm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='terms',
            table='terms',
        ),
    ]
