# Generated by Django 4.2.9 on 2024-01-17 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUOM',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=30)),
                ('uom', models.CharField(db_column='UOM', max_length=8)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=8, max_digits=25)),
                ('shelf', models.CharField(db_column='Shelf', max_length=20, null=True)),
                ('price', models.DecimalField(db_column='Price', decimal_places=8, max_digits=25, null=True)),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=8, max_digits=25, null=True)),
                ('realcost', models.DecimalField(db_column='RealCost', decimal_places=8, max_digits=25, null=True)),
                ('mostrecentlycost', models.DecimalField(db_column='MostRecentlyCost', decimal_places=8, max_digits=25, null=True)),
                ('minsaleprice', models.DecimalField(db_column='MinSalePrice', decimal_places=8, max_digits=25, null=True)),
                ('maxsaleprice', models.DecimalField(db_column='MaxSalePrice', decimal_places=8, max_digits=25, null=True)),
                ('minpurchaseprice', models.DecimalField(db_column='MinPurchasePrice', decimal_places=8, max_digits=25, null=True)),
                ('maxpurchaseprice', models.DecimalField(db_column='MaxPurchasePrice', decimal_places=8, max_digits=25, null=True)),
                ('minqty', models.DecimalField(db_column='MinQty', decimal_places=8, max_digits=25, null=True)),
                ('maxqty', models.DecimalField(db_column='MaxQty', decimal_places=8, max_digits=25, null=True)),
                ('normallevel', models.DecimalField(db_column='NormalLevel', decimal_places=8, max_digits=25, null=True)),
                ('reolelvel', models.DecimalField(db_column='ReOLevel', decimal_places=8, max_digits=25, null=True)),
                ('reoqty', models.DecimalField(db_column='ReOQty', decimal_places=8, max_digits=25, null=True)),
                ('foclevel', models.DecimalField(db_column='FOCLevel', decimal_places=8, max_digits=25, null=True)),
                ('focqty', models.DecimalField(db_column='FOCQty', decimal_places=8, max_digits=25, null=True)),
                ('bonuspointqty', models.DecimalField(db_column='BonusPointQty', decimal_places=8, max_digits=25, null=True)),
                ('bonuspoint', models.DecimalField(db_column='Bonuspoint', decimal_places=2, max_digits=19, null=True)),
                ('weight', models.DecimalField(db_column='Weight', decimal_places=8, max_digits=25, null=True)),
                ('weightuom', models.CharField(db_column='WeightUOM', max_length=8, null=True)),
                ('volume', models.DecimalField(db_column='Volume', decimal_places=8, max_digits=25, null=True)),
                ('voumeuom', models.CharField(db_column='VolumeUOM', max_length=8, null=True)),
                ('barcode', models.CharField(db_column='Barcode', max_length=30, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('redeembonuspoint', models.DecimalField(db_column='RedeemBonuesPoint', decimal_places=2, max_digits=19, null=True)),
                ('csgnqty', models.DecimalField(db_column='CSGNQty', decimal_places=8, max_digits=25, null=True)),
                ('price2', models.DecimalField(db_column='Price2', decimal_places=8, max_digits=25, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('price3', models.DecimalField(db_column='Price3', decimal_places=8, max_digits=25, null=True)),
                ('price4', models.DecimalField(db_column='Price4', decimal_places=8, max_digits=25, null=True)),
                ('price5', models.DecimalField(db_column='Price5', decimal_places=8, max_digits=25, null=True)),
                ('price6', models.DecimalField(db_column='Price6', decimal_places=8, max_digits=25, null=True)),
                ('markupratio', models.DecimalField(db_column='MarkupRatio', decimal_places=6, max_digits=18, null=True)),
                ('markdownratio2', models.DecimalField(db_column='MarkdownRatio2', decimal_places=6, max_digits=18, null=True)),
                ('markdownratio3', models.DecimalField(db_column='MarkdownRatio3', decimal_places=6, max_digits=18, null=True)),
                ('markdownratio4', models.DecimalField(db_column='MarkdownRatio4', decimal_places=6, max_digits=18, null=True)),
                ('markdownratio5', models.DecimalField(db_column='MarkdownRatio5', decimal_places=6, max_digits=18, null=True)),
                ('markdownratio6', models.DecimalField(db_column='MarkdownRatio6', decimal_places=6, max_digits=18, null=True)),
                ('markdownratiominprice', models.DecimalField(db_column='MarkdownRatioMinPrice', decimal_places=6, max_digits=18, null=True)),
                ('markdownratiomaxprice', models.DecimalField(db_column='MarkdownRatioMaxPrice', decimal_places=6, max_digits=18, null=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUOMCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'ItemUOM',
                'ordering': ('itemcode',),
                'managed': True,
            },
        ),
    ]
