# Generated by Django 4.2.9 on 2024-01-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('itemuom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemuom',
            options={'managed': True, 'ordering': ('uom',)},
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUOMItemCode', to='item.item'),
        ),
    ]
