# Generated by Django 4.2.9 on 2024-02-02 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_itemcode'),
        ('itemuom', '0002_alter_itemuom_options_alter_itemuom_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuom',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemUOMItemCode', to='item.item', to_field='itemcode'),
        ),
    ]
