# Generated by Django 4.2.9 on 2024-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemuom', '0003_alter_itemuom_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuom',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32),
        ),
    ]
