# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemuom', '0004_alter_itemuom_guid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemuom',
            table='itemuom',
        ),
    ]
