# Generated by Django 4.2.17 on 2025-01-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemuom', '0005_alter_itemuom_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuom',
            name='udfcalmethod',
            field=models.CharField(db_column='UdfCalMethod', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='itemuom',
            name='udfcalrate',
            field=models.DecimalField(db_column='UdfCalRate', decimal_places=2, max_digits=2, null=True),
        ),
    ]
