# Generated by Django 4.2.17 on 2025-02-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemuom', '0006_itemuom_udfcalmethod_itemuom_udfcalrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemuom',
            name='udfpallet',
            field=models.SmallIntegerField(blank=True, db_column='UdfPallet', default=0, null=True),
        ),
    ]
