# Generated by Django 4.2.9 on 2024-01-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itembrand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembrand',
            options={'managed': True, 'ordering': ('itembrand',)},
        ),
        migrations.AddField(
            model_name='itembrand',
            name='itembrand',
            field=models.CharField(db_column='ItemBrand', default=1, max_length=20),
            preserve_default=False,
        ),
    ]
