# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itembrand', '0003_alter_itembrand_markupratio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itembrand',
            table='itembrand',
        ),
    ]
