# Generated by Django 4.2.17 on 2024-12-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lorry',
            fields=[
                ('lorryguid', models.CharField(db_column='LorryGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('lorrynumber', models.CharField(db_column='LorryNumber', max_length=30)),
                ('docdate', models.DateTimeField(db_column='DocDate')),
            ],
            options={
                'db_table': 'lorry',
                'ordering': ('lorryguid',),
                'managed': True,
            },
        ),
    ]
