# Generated by Django 4.2.17 on 2025-01-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lorryplate', '0001_initial'),
        ('lorry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorry',
            name='lorrynumber',
            field=models.ForeignKey(db_column='LorryNumber', on_delete=django.db.models.deletion.DO_NOTHING, related_name='LorryLorryNumber', to='lorryplate.lorryplate', to_field='lorrynumber'),
        ),
    ]
