# Generated by Django 4.2.9 on 2024-01-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=30)),
                ('batchno', models.CharField(db_column='BatchNo', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=40, null=True)),
                ('manufactureddate', models.DateTimeField(db_column='ManufacturedDate', editable=False, null=True)),
                ('expirydate', models.DateTimeField(db_column='ExpiryDate', editable=False, null=True)),
                ('lastsaledate', models.DateTimeField(db_column='LastSaleDate', editable=False, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemBatchCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'ItemBatch',
                'ordering': ('itemcode',),
                'managed': True,
            },
        ),
    ]
