# Generated by Django 4.2.9 on 2024-01-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itembatch', '0002_alter_itembatch_itemcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembatch',
            options={'managed': True, 'ordering': ('batchno',)},
        ),
    ]
