# Generated by Django 4.2.9 on 2024-02-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_location'),
        ('item', '0005_alter_item_guid'),
        ('prdtl', '0004_alter_prdtl_autokey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdtl',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PRDTLItemCodeAutokey', to='item.item', to_field='itemcode'),
        ),
        migrations.AlterField(
            model_name='prdtl',
            name='location',
            field=models.ForeignKey(db_column='Location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='PRDTLLocationAutokey', to='location.location', to_field='location'),
        ),
    ]
