# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prdtl', '0005_alter_prdtl_itemcode_alter_prdtl_location'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prdtl',
            table='prdtl',
        ),
    ]
