# Generated by Django 4.2.17 on 2024-12-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemclass', '0005_remove_itemclass_autokey_itemclass_itemclassguid'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDtl',
            fields=[
                ('transactiondtlguid', models.CharField(db_column='TransactionDtlGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=80)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('qty', models.DecimalField(db_column='Qty', decimal_places=8, max_digits=25, null=True)),
                ('subtotal', models.DecimalField(db_column='SubTotal', decimal_places=2, max_digits=19, null=True)),
                ('itemclassguid', models.ForeignKey(db_column='ItemClassGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransactionDtlItemClassGuid', to='itemclass.itemclass')),
                ('transactionguid', models.ForeignKey(db_column='TransactionGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransactionDtlTransactionGuid', to='transaction.transaction')),
            ],
        ),
    ]
