# Generated by Django 4.2.17 on 2024-12-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiondtl',
            options={'managed': True, 'ordering': ('transactiondtlguid',)},
        ),
        migrations.AlterModelTable(
            name='transactiondtl',
            table='transactiondtl',
        ),
    ]
