# Generated by Django 4.2.17 on 2025-01-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0006_alter_itemclass_itemclass'),
        ('transactiondtl', '0002_alter_transactiondtl_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondtl',
            name='itemclassguid',
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='ItemClass',
            field=models.ForeignKey(db_column='ItemClass', default='NA', on_delete=django.db.models.deletion.DO_NOTHING, related_name='TransactionDtlItemClass', to='itemclass.itemclass', to_field='itemclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='udfcommtype',
            field=models.CharField(db_column='UdfCommType', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='udfcommvalue',
            field=models.CharField(db_column='udfcommvalue', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='uom',
            field=models.CharField(db_column='Uom', max_length=30, null=True),
        ),
    ]
