# Generated by Django 4.2.17 on 2025-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0003_remove_transactiondtl_itemclassguid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondtl',
            old_name='ItemClass',
            new_name='itemclass',
        ),
        migrations.AlterField(
            model_name='transactiondtl',
            name='udfcommtype',
            field=models.CharField(db_column='udfCommType', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondtl',
            name='udfcommvalue',
            field=models.CharField(db_column='udfCommValue', max_length=30, null=True),
        ),
    ]
