# Generated by Django 4.2.17 on 2025-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0004_rename_itemclass_transactiondtl_itemclass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondtl',
            name='udfcommtype',
        ),
        migrations.RemoveField(
            model_name='transactiondtl',
            name='udfcommvalue',
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='commtype',
            field=models.CharField(db_column='CommType', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='commvalue',
            field=models.CharField(db_column='CommValue', max_length=30, null=True),
        ),
    ]
