# Generated by Django 4.2.17 on 2025-01-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0005_remove_transactiondtl_udfcommtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondtl',
            name='qty',
            field=models.DecimalField(db_column='Qty', decimal_places=2, max_digits=25, null=True),
        ),
    ]
