# Generated by Django 4.2.17 on 2025-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0007_alter_transactiondtl_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondtl',
            name='commvalue',
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='udfcalmethod',
            field=models.CharField(db_column='UdfCalMethod', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transactiondtl',
            name='udfcalrate',
            field=models.DecimalField(db_column='UdfCalRate', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='transactiondtl',
            name='qty',
            field=models.DecimalField(db_column='Qty', decimal_places=8, max_digits=25, null=True),
        ),
    ]
