# Generated by Django 4.2.17 on 2025-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0008_remove_transactiondtl_commvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondtl',
            name='isqtyupdated',
            field=models.BooleanField(db_column='IsQtyUpdated', default=False),
        ),
    ]
