# Generated by Django 4.2.17 on 2025-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactiondtl', '0009_transactiondtl_isqtyupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondtl',
            name='udfispallet',
            field=models.SmallIntegerField(blank=True, db_column='UdfIsPallet', default=0, null=True),
        ),
    ]
