# Generated by Django 4.2.9 on 2024-01-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_alter_terms_companyautokey'),
        ('po', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='displayterm',
            field=models.ForeignKey(db_column='DisplayTerm', on_delete=django.db.models.deletion.DO_NOTHING, related_name='POTermsDisplayTerm', to='terms.terms'),
        ),
    ]
