# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_alter_po_displayterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='calcdiscountonunitprice',
            field=models.CharField(db_column='CalcDiscountOnUnitPrice', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='po',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='po',
            name='cantransferbyvalue',
            field=models.CharField(db_column='CanTransferByValue', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='currencyrate',
            field=models.DecimalField(db_column='CurrencyRate', decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='po',
            name='inclusivetax',
            field=models.CharField(db_column='InclusiveTax', max_length=1),
        ),
        migrations.AlterField(
            model_name='po',
            name='isroundadj',
            field=models.CharField(db_column='IsRoundAdj', max_length=1),
        ),
        migrations.AlterField(
            model_name='po',
            name='totaxcurrencyrate',
            field=models.DecimalField(db_column='ToTaxCurrencyRate', decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='po',
            name='transferable',
            field=models.CharField(db_column='Transferable', max_length=1),
        ),
    ]
