# Generated by Django 4.2.9 on 2024-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_alter_po_calcdiscountonunitprice_alter_po_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='autokey',
            field=models.CharField(db_column='AutoKey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
