# Generated by Django 5.0.1 on 2024-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('autokey', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('registrationnum', models.CharField(editable=False, max_length=32, unique=True)),
            ],
            options={
                'db_table': 'Company',
                'ordering': ('code',),
                'managed': True,
            },
        ),
    ]
