# Generated by Django 5.0.1 on 2024-01-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_autokey_alter_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(db_column='Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='autokey',
            field=models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_column='Code', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registrationnum',
            field=models.CharField(db_column='RegistrationNum', max_length=32, unique=True),
        ),
    ]
