# Generated by Django 4.2.9 on 2024-01-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(db_column='Name', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
