# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
