# Generated by Django 4.2.9 on 2024-01-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dn',
            name='calcdiscountonunitprice',
            field=models.CharField(db_column='CalcDiscountOnUnitPrice', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='dn',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='dn',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='dn',
            name='inclusivetax',
            field=models.CharField(db_column='InclusiveTax', max_length=1),
        ),
        migrations.AlterField(
            model_name='dn',
            name='posttogl',
            field=models.CharField(db_column='PostToGL', max_length=1),
        ),
        migrations.AlterField(
            model_name='dn',
            name='posttostock',
            field=models.CharField(db_column='PostToStock', max_length=1),
        ),
        migrations.AlterField(
            model_name='dn',
            name='reallocatepurchasebyproject',
            field=models.CharField(db_column='ReallocatePurchaseByProject', max_length=1),
        ),
    ]
