# Generated by Django 4.2.9 on 2024-01-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0002_alter_dn_calcdiscountonunitprice_alter_dn_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dn',
            name='currencycode',
            field=models.CharField(db_column='CurrencyCode', max_length=5),
        ),
        migrations.AlterField(
            model_name='dn',
            name='debtorname',
            field=models.CharField(db_column='DebtorName', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dn',
            name='printcount',
            field=models.SmallIntegerField(db_column='PrintCount'),
        ),
        migrations.AlterField(
            model_name='dn',
            name='reallocatepurchasebyprojectjedockey',
            field=models.BigIntegerField(db_column='ReallocatePurchaseByProjectJEDocKey', null=True),
        ),
        migrations.AlterField(
            model_name='dn',
            name='reallocatepurchasebyprojectno',
            field=models.CharField(db_column='ReallocatePurchaseByProjectNo', max_length=10, null=True),
        ),
    ]
