# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dn', '0003_alter_dn_currencycode_alter_dn_debtorname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dn',
            table='dn',
        ),
    ]
