# Generated by Django 4.2.17 on 2024-12-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crewdtl',
            fields=[
                ('crewdtlguid', models.CharField(db_column='CrewDtlGuid', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemclass', models.CharField(db_column='ItemClass', max_length=50, null=True)),
                ('commtype', models.CharField(db_column='CommType', max_length=100, null=True)),
                ('commvalue', models.DecimalField(db_column='CommValue', decimal_places=4, max_digits=5, null=True)),
                ('documentsum', models.DecimalField(db_column='DocumentSum', decimal_places=4, max_digits=25, null=True)),
                ('calculatedcomm', models.DecimalField(db_column='CalculatedComm', decimal_places=4, max_digits=5, null=True)),
                ('crewguid', models.ForeignKey(db_column='CrewGuid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CrewDtlCrewGuid', to='crew.crew')),
            ],
            options={
                'db_table': 'crewdtl',
                'ordering': ('crewdtlguid',),
                'managed': True,
            },
        ),
    ]
