# Generated by Django 4.2.17 on 2025-01-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemclass', '0006_alter_itemclass_itemclass'),
        ('crewdtl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdtl',
            name='calculationtype',
            field=models.CharField(db_column='CalculationType', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crewdtl',
            name='totalamount',
            field=models.DecimalField(db_column='TotalAmount', decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='crewdtl',
            name='totalqty',
            field=models.DecimalField(db_column='TotalQty', decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='crewdtl',
            name='itemclass',
            field=models.ForeignKey(db_column='ItemClass', default='NA', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CrewdtlItemClass', to='itemclass.itemclass', to_field='itemclass'),
            preserve_default=False,
        ),
    ]
