# Generated by Django 4.2.17 on 2025-01-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0002_crewdtl_calculationtype_crewdtl_totalamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdtl',
            name='share',
            field=models.DecimalField(db_column='Share', decimal_places=2, max_digits=2, null=True),
        ),
    ]
