# Generated by Django 4.2.17 on 2025-01-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0003_crewdtl_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdtl',
            name='share',
            field=models.SmallIntegerField(db_column='Share', null=True),
        ),
    ]
