# Generated by Django 4.2.17 on 2025-01-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0004_alter_crewdtl_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdtl',
            name='uom',
            field=models.CharField(db_column='Uom', max_length=10, null=True),
        ),
    ]
