# Generated by Django 4.2.17 on 2025-01-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0005_crewdtl_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdtl',
            name='udfcalmethod',
            field=models.CharField(db_column='UdfCalMethod', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='crewdtl',
            name='udfcalrate',
            field=models.DecimalField(db_column='UdfCalRate', decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='crewdtl',
            name='totalqty',
            field=models.DecimalField(db_column='TotalQty', decimal_places=8, max_digits=8, null=True),
        ),
    ]
