# Generated by Django 4.2.17 on 2025-01-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0006_crewdtl_udfcalmethod_crewdtl_udfcalrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdtl',
            name='totalqty',
            field=models.DecimalField(db_column='TotalQty', decimal_places=8, max_digits=25, null=True),
        ),
    ]
