# Generated by Django 4.2.17 on 2025-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0007_alter_crewdtl_totalqty'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='crewdtl',
        #     name='udfcalmethod',
        #     field=models.CharField(db_column='UdfCalMethod', max_length=8, null=True),
        # ),
        # migrations.AddField(
        #     model_name='crewdtl',
        #     name='udfcalrate',
        #     field=models.DecimalField(db_column='UdfCalRate', decimal_places=2, max_digits=2, null=True),
        # ),
        migrations.AlterField(
            model_name='crewdtl',
            name='calculatedcomm',
            field=models.DecimalField(db_column='CalculatedComm', decimal_places=8, max_digits=25, null=True),
        ),
    ]
