# Generated by Django 4.2.17 on 2025-01-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewdtl', '0008_crewdtl_udfcalmethod_crewdtl_udfcalrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewdtl',
            name='commvalue',
            field=models.DecimalField(db_column='CommValue', decimal_places=7, max_digits=8, null=True),
        ),
    ]
