# Generated by Django 4.2.9 on 2024-01-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('itemcategory', models.CharField(db_column='ItemCategory', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=40, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=40, null=True)),
                ('note', models.CharField(db_column='Note', max_length=40, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('shortcode', models.CharField(db_column='ShortCode', max_length=8, null=True)),
                ('markupratio', models.DecimalField(db_column='MarkupRatio', decimal_places=6, max_digits=18, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemCategoryCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'ItemCategory',
                'ordering': ('itemcategory',),
                'managed': True,
            },
        ),
    ]
