# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='note',
            field=models.CharField(db_column='Note', max_length=255, null=True),
        ),
    ]
