# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemcategory', '0002_alter_itemcategory_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemcategory',
            table='itemcategory',
        ),
    ]
