# Generated by Django 4.2.9 on 2024-01-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtorType',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('debtortype', models.CharField(db_column='DebtorType', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=40, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=40, null=True)),
                ('isactive', models.CharField(db_column='IsActive', max_length=5)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('guid', models.CharField(db_column='Guid', max_length=32, null=True, unique=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='DebtorTypeCompanyAutokey', to='company.company')),
            ],
            options={
                'db_table': 'DebtorType',
                'ordering': ('debtortype',),
                'managed': True,
            },
        ),
    ]
