# Generated by Django 4.2.9 on 2024-01-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtortype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtortype',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32, unique=True),
        ),
    ]
