# Generated by Django 4.2.9 on 2024-01-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtortype', '0002_alter_debotortype_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtortype',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32),
        ),
    ]
