# Generated by Django 4.2.9 on 2024-01-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtortype', '0003_alter_debtortype_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtortype',
            name='guid',
            field=models.CharField(db_column='Guid', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='debtortype',
            name='isactive',
            field=models.CharField(db_column='IsActive', max_length=1),
        ),
    ]
