# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtortype', '0004_alter_debtortype_guid_alter_debtortype_isactive'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debtortype',
            table='debtortype',
        ),
    ]
