# Generated by Django 4.2.17 on 2026-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcItem',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('mainsupplier', models.CharField(db_column='MainSupplier', max_length=30)),
                ('itemcode', models.CharField(db_column='ItemCode', max_length=30, unique=True)),
                ('itemgroup', models.CharField(db_column='ItemGroup', max_length=30, null=True)),
                ('itemtype', models.CharField(db_column='ItemType', max_length=30, null=True)),
                ('itembrand', models.CharField(db_column='ItemBrand', max_length=30, null=True)),
                ('itemcategory', models.CharField(db_column='ItemCategory', max_length=30, null=True)),
                ('itemclass', models.CharField(db_column='ItemClass', max_length=30, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('desc2', models.CharField(db_column='Desc2', max_length=100, null=True)),
                ('furtherdescription', models.CharField(db_column='FurtherDescription', max_length=255, null=True)),
                ('assemblycost', models.DecimalField(db_column='AssemblyCost', decimal_places=8, max_digits=25, null=True)),
                ('leadtime', models.CharField(db_column='LeadTime', max_length=40, null=True)),
                ('stockcontrol', models.CharField(db_column='StockControl', max_length=5)),
                ('hasserialno', models.CharField(db_column='HasSerialNo', max_length=5)),
                ('hasbatchno', models.CharField(db_column='HasBatchNo', max_length=5)),
                ('dutyrate', models.DecimalField(db_column='DutyRate', decimal_places=6, max_digits=18)),
                ('note', models.CharField(db_column='Note', max_length=255, null=True)),
                ('image', models.BinaryField(db_column='Image', null=True)),
                ('costingmethod', models.SmallIntegerField(db_column='CostingMethod')),
                ('salesuom', models.CharField(db_column='SalesUOM', max_length=8)),
                ('purchaseuom', models.CharField(db_column='PurchaseUOM', max_length=8)),
                ('reportuom', models.CharField(db_column='ReportUOM', max_length=8)),
                ('lastmodified', models.DateTimeField(db_column='LastModified')),
                ('lastmodifieduserid', models.CharField(db_column='LastModifiedUserID', max_length=10)),
                ('createdtimestamp', models.DateTimeField(auto_now=True, db_column='CreatedTimeStamp')),
                ('createduserid', models.CharField(db_column='CreatedUserID', max_length=10)),
                ('isactive', models.CharField(db_column='IsActive', max_length=5)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('snformatname', models.CharField(db_column='SNFormatName', max_length=5, null=True)),
                ('iscalcbonuspoint', models.CharField(db_column='IsCalcBonusPoint', max_length=5, null=True)),
                ('markupratio', models.DecimalField(db_column='MarkupRatio', decimal_places=6, max_digits=18, null=True)),
                ('haspromoter', models.CharField(db_column='HasPromoter', max_length=5)),
                ('globalcode', models.CharField(db_column='GlobalCode', max_length=30, null=True)),
                ('leadtimeday', models.IntegerField(db_column='LeadTimeDay', null=True)),
                ('externallink', models.CharField(db_column='ExternalLink', max_length=255, null=True)),
                ('discontinued', models.CharField(db_column='Discontinued', max_length=5)),
                ('autouomconversion', models.CharField(db_column='AutoUOMConversion', max_length=5, null=True)),
                ('baseuom', models.CharField(db_column='BaseUOM', max_length=8)),
                ('backordercontrol', models.CharField(db_column='BackOrderCOntrol', max_length=5)),
                ('tariffcode', models.CharField(db_column='TariffCode', max_length=12, null=True)),
                ('guid', models.CharField(db_column='Guid', max_length=32)),
                ('issalesitem', models.CharField(db_column='IsSalesItem', max_length=5, null=True)),
                ('ispurchaseitem', models.CharField(db_column='IsPurchaseItem', max_length=5, null=True)),
                ('ispositem', models.CharField(db_column='IspOSItem', max_length=5, null=True)),
                ('israwmeterialitem', models.CharField(db_column='IsRawMaterialItem', max_length=5, null=True)),
                ('isfinishgoodsitem', models.CharField(db_column='IsFinishGoodsItem', max_length=5, null=True)),
                ('imagefilename', models.CharField(db_column='ImageFileName', max_length=120, null=True)),
            ],
            options={
                'db_table': 'item',
                'ordering': ('itemcode',),
                'managed': False,
            },
        ),
    ]
