# Generated by Django 4.2.9 on 2024-02-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0004_alter_creditor_accno_alter_creditor_companyname'),
        ('terms', '0005_alter_terms_displayterm'),
        ('pr', '0002_alter_pr_calcdiscountonunitprice_alter_pr_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pr',
            name='creditorcode',
            field=models.ForeignKey(db_column='CreditorCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PRCreditorAccNo', to='creditor.creditor', to_field='accno'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='creditorname',
            field=models.ForeignKey(db_column='CreditorName', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PRCreditorCompanyName', to='creditor.creditor', to_field='companyname'),
        ),
        migrations.AlterField(
            model_name='pr',
            name='displayterm',
            field=models.ForeignKey(db_column='DisplayTerm', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PRDisplayTerm', to='terms.terms', to_field='displayterm'),
        ),
    ]
