# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemtype',
            table='itemtype',
        ),
    ]
