# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivdtl', '0002_alter_ivdtl_itemcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ivdtl',
            table='ivdtl',
        ),
    ]
