# Generated by Django 4.2.17 on 2026-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcTerms',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('displayterm', models.CharField(db_column='DisplayTerm', max_length=50, unique=True)),
                ('terms', models.CharField(db_column='Terms', max_length=30, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('termtype', models.CharField(db_column='Termtype', max_length=40, null=True)),
                ('termdays', models.IntegerField(db_column='TermDays', null=True)),
                ('discountdays', models.IntegerField(db_column='DiscountDays', null=True)),
                ('discountpercent', models.DecimalField(db_column='DiscountPercent', decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'terms',
                'ordering': ('autokey',),
                'managed': False,
            },
        ),
    ]
