# Generated by Django 4.2.9 on 2024-01-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_alter_company_autokey'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('uom', models.CharField(db_column='UOM', max_length=8)),
                ('pricecategory', models.CharField(db_column='PriceCategory', max_length=12, null=True)),
                ('accno', models.CharField(db_column='AccNo', max_length=12, null=True)),
                ('suppcustitemcode', models.CharField(db_column='SuppCustItemCode', max_length=30, null=True)),
                ('ref', models.CharField(db_column='Ref', max_length=80, null=True)),
                ('usefixedprice', models.CharField(db_column='UseFixedPrice', max_length=5)),
                ('fixedprice', models.DecimalField(db_column='FixedPrice', decimal_places=8, max_digits=25, null=True)),
                ('fixeddetaildiscount', models.CharField(db_column='FixedDetailDiscount', max_length=20, null=True)),
                ('qty1', models.DecimalField(db_column='Qty1', decimal_places=8, max_digits=25, null=True)),
                ('price1', models.DecimalField(db_column='Price1', decimal_places=8, max_digits=25, null=True)),
                ('detaildiscount1', models.CharField(db_column='DetailDiscount1', max_length=20, null=True)),
                ('qty2', models.DecimalField(db_column='Qty2', decimal_places=8, max_digits=25, null=True)),
                ('price2', models.DecimalField(db_column='Price2', decimal_places=8, max_digits=25, null=True)),
                ('detaildiscount2', models.CharField(db_column='DetailDiscount2', max_length=20, null=True)),
                ('qty3', models.DecimalField(db_column='Qty3', decimal_places=8, max_digits=25, null=True)),
                ('price3', models.DecimalField(db_column='Price3', decimal_places=8, max_digits=25, null=True)),
                ('detaildiscount3', models.CharField(db_column='DetailDiscount3', max_length=20, null=True)),
                ('qty4', models.DecimalField(db_column='Qty4', decimal_places=8, max_digits=25, null=True)),
                ('price4', models.DecimalField(db_column='Price4', decimal_places=8, max_digits=25, null=True)),
                ('detaildiscount4', models.CharField(db_column='DetailDiscount4', max_length=20, null=True)),
                ('foclevel', models.DecimalField(db_column='FOCLevel', decimal_places=8, max_digits=25, null=True)),
                ('focqty', models.DecimalField(db_column='FOCQty', decimal_places=8, max_digits=25, null=True)),
                ('bonuspointqty', models.DecimalField(db_column='BonusPointQty', decimal_places=8, max_digits=25, null=True)),
                ('bonuspoint', models.DecimalField(db_column='Bonuspoint', decimal_places=2, max_digits=19, null=True)),
                ('lastupdate', models.IntegerField(db_column='LastUpdate')),
                ('guid', models.CharField(db_column='Guid', max_length=32, unique=True)),
                ('companyautokey', models.ForeignKey(db_column='CompanyAutoKey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemPriceCompanyAutokey', to='company.company')),
                ('itemcode', models.ForeignKey(db_column='ItemCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemPriceItemCode', to='item.item')),
            ],
            options={
                'db_table': 'ItemPrice',
                'ordering': ('pricecategory',),
                'managed': True,
            },
        ),
    ]
