# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('itemprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='bonuspoint',
            field=models.DecimalField(db_column='BonusPoint', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ItemPriceItemCode', to='item.item'),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='usefixedprice',
            field=models.CharField(db_column='UseFixedPrice', max_length=1),
        ),
    ]
