# Generated by Django 5.0.1 on 2024-01-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_company_address_alter_company_autokey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('autokey', models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=32, unique=True)),
                ('address', models.CharField(db_column='Address', max_length=255)),
                ('registrationnum', models.CharField(db_column='RegistrationNum', max_length=32, unique=True)),
                ('companyautokey', models.ForeignKey(db_column='Company_autokey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Company_autokey', to='company.company')),
            ],
            options={
                'db_table': 'Branch',
                'ordering': ('code',),
                'managed': True,
            },
        ),
    ]
