# Generated by Django 5.0.1 on 2024-01-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
        ('company', '0003_alter_company_address_alter_company_autokey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='companyautokey',
            field=models.ForeignKey(db_column='Company_autokey', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CompanyAutokey', to='company.company'),
        ),
    ]
