# Generated by Django 4.2.9 on 2024-01-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_companyautokey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='registrationnum',
        ),
        migrations.AddField(
            model_name='branch',
            name='registorno',
            field=models.CharField(db_column='RegistorNo', default=1, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='autokey',
            field=models.CharField(db_column='Autokey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
