# Generated by Django 4.2.14 on 2024-07-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_remove_branch_registrationnum_branch_registorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(db_column='Address', max_length=255, unique=True),
        ),
    ]
