# Generated by Django 4.2.17 on 2024-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_alter_branch_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
