# Generated by Django 4.2.17 on 2025-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_branch_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, db_column='Code', max_length=32),
        ),
        migrations.AlterField(
            model_name='branch',
            name='registorno',
            field=models.CharField(blank=True, db_column='RegistorNo', max_length=32),
        ),
    ]
