# Generated by Django 4.2.16 on 2024-10-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_alter_item_mainsupplier'),
        ('cndtl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cndtl',
            name='itemcode',
            field=models.ForeignKey(db_column='ItemCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CNDTLItemCodeAutokey', to='item.item', to_field='itemcode'),
        ),
    ]
