# Generated by Django 4.2.9 on 2024-03-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr',
            name='createdtimestamp',
            field=models.DateTimeField(auto_now=True, db_column='CreatedTimeStamp'),
        ),
    ]
