# Generated by Django 4.2.9 on 2024-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0002_alter_pi_displayterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='calcdiscountonunitprice',
            field=models.CharField(db_column='CalcDiscountOnUnitPrice', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='cancelled',
            field=models.CharField(db_column='Cancelled', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='cansync',
            field=models.CharField(db_column='CanSync', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='inclusivetax',
            field=models.CharField(db_column='InclusiveTax', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='isroundadj',
            field=models.CharField(db_column='IsRoundAdj', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='posttogl',
            field=models.CharField(db_column='PostToGL', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='posttostock',
            field=models.CharField(db_column='PostToStock', max_length=1),
        ),
        migrations.AlterField(
            model_name='pi',
            name='printcount',
            field=models.SmallIntegerField(db_column='PrintCount'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='roundadj',
            field=models.DecimalField(db_column='RoundAdj', decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='transferable',
            field=models.CharField(db_column='Transferable', max_length=1),
        ),
    ]
