# Generated by Django 4.2.9 on 2024-02-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0004_alter_creditor_accno_alter_creditor_companyname'),
        ('pi', '0003_alter_pi_calcdiscountonunitprice_alter_pi_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='creditorcode',
            field=models.ForeignKey(db_column='CreditorCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CreditorAccNo', to='creditor.creditor', to_field='accno'),
        ),
    ]
