# Generated by Django 4.2.9 on 2024-02-19 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0004_alter_creditor_accno_alter_creditor_companyname'),
        ('pi', '0004_alter_pi_creditorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='creditorname',
            field=models.ForeignKey(db_column='CreditorName', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CreditorCompanyName', to='creditor.creditor', to_field='companyname'),
        ),
    ]
