# Generated by Django 4.2.9 on 2024-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0005_alter_pi_creditorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='docdate',
            field=models.DateField(db_column='DocDate'),
        ),
    ]
