# Generated by Django 4.2.9 on 2024-02-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0006_alter_pi_docdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='docdate2',
            field=models.DateField(db_column='DocDate2', null=True),
        ),
        migrations.AlterField(
            model_name='pi',
            name='taxdate',
            field=models.DateField(db_column='TaxDate', null=True),
        ),
    ]
