# Generated by Django 4.2.9 on 2024-02-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0003_alter_terms_displayterm'),
        ('pi', '0008_alter_pi_docdate_alter_pi_docdate2_alter_pi_taxdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='displayterm',
            field=models.ForeignKey(db_column='DisplayTerm', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PITermsDisplayTerm', to='terms.terms', to_field='displayterm'),
        ),
    ]
