# Generated by Django 4.2.9 on 2024-02-19 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0005_alter_terms_displayterm'),
        ('pi', '0010_alter_pi_displayterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='displayterm',
            field=models.ForeignKey(db_column='DisplayTerm', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PITermsDisplayTerm', to='terms.terms', to_field='displayterm'),
        ),
    ]
