# Generated by Django 4.2.9 on 2024-02-19 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditor', '0004_alter_creditor_accno_alter_creditor_companyname'),
        ('terms', '0005_alter_terms_displayterm'),
        ('pi', '0011_alter_pi_displayterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='creditorcode',
            field=models.ForeignKey(db_column='CreditorCode', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PICreditorAccNo', to='creditor.creditor', to_field='accno'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='creditorname',
            field=models.ForeignKey(db_column='CreditorName', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PICreditorCompanyName', to='creditor.creditor', to_field='companyname'),
        ),
        migrations.AlterField(
            model_name='pi',
            name='displayterm',
            field=models.ForeignKey(db_column='DisplayTerm', on_delete=django.db.models.deletion.DO_NOTHING, related_name='PIDisplayTerm', to='terms.terms', to_field='displayterm'),
        ),
    ]
