# Generated by Django 4.2.9 on 2024-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0012_alter_pi_creditorcode_alter_pi_creditorname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi',
            name='autokey',
            field=models.CharField(db_column='AutoKey', editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
