"""
Django settings for autocount_dashboard project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from datetime import datetime,timedelta
from pathlib import Path

import environ

env = environ.Env()
environ.Env.read_env()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yr1nj5%p9#158-c5twd61uel^1q7@yxrb15t@(eu&!$(6^xlmg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     #Add in new*************************************************
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_filters',
    "drf_spectacular",
    "debug_toolbar",
    # My apps
    'company.apps.CompanyConfig',
    'branch.apps.BranchConfig',
    'terms.apps.TermsConfig',
    'location.apps.LocationConfig',
    'debtor.apps.DebtorConfig',
    'debtortype.apps.DebtortypeConfig',
    'creditor.apps.CreditorConfig',
    'creditortype.apps.CreditortypeConfig',
    'itemgroup.apps.ItemgroupConfig',
    'itemtype.apps.ItemtypeConfig',
    'taxtype.apps.TaxtypeConfig',
    'itembrand.apps.ItembrandConfig',
    'itemclass.apps.ItemclassConfig',
    'itemcategory.apps.ItemcategoryConfig',
    'item.apps.ItemConfig',
    'itembatch.apps.ItembatchConfig',
    'itembom.apps.ItembomConfig',
    'itemuom.apps.ItemuomConfig',
    'itemprice.apps.ItempriceConfig',
    'po.apps.PoConfig',
    'podtl.apps.PodtlConfig',
    'pi.apps.PiConfig',
    'pidtl.apps.PidtlConfig',
    'pr.apps.PrConfig',
    'prdtl.apps.PrdtlConfig',
    'so.apps.SoConfig',
    'sodtl.apps.SodtlConfig',
    'cn.apps.CnConfig',
    'cndtl.apps.CndtlConfig',
    'dn.apps.DnConfig',
    'dndtl.apps.DndtlConfig',
    'adj.apps.AdjConfig',
    'adjdtl.apps.AdjdtlConfig',
    'iv.apps.IvConfig',
    'ivdtl.apps.IvdtlConfig',
    'filereader.apps.FilereaderConfig',
    'posthandler.apps.PosthandlerConfig',
    'gr.apps.GrConfig',
    'grdtl.apps.GrdtlConfig',
    'salesagent.apps.SalesagentConfig',
    'commissionitemclass.apps.CommissionitemclassConfig',
    'crewrate.apps.CrewrateConfig',
    'crewratedtl.apps.CrewratedtlConfig',
    'lorry.apps.LorryConfig',
    'lorryplate.apps.LorryplateConfig',
    'crew.apps.CrewConfig',
    'crewdtl.apps.CrewdtlConfig',
    'transaction.apps.TransactionConfig',
    'transactiondtl.apps.TransactiondtlConfig',
    'acitem.apps.AcitemConfig',
    'acitemuom.apps.AcitemuomConfig',
    'acsalesagent.apps.AcsalesagentConfig',
    'acterms.apps.ActermsConfig',
    'acdebtor.apps.AcdebtorConfig',
    'aciv.apps.AcivConfig',
    'acivdtl.apps.AcivdtlConfig',
]

####ADD

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS":"drf_spectacular.openapi.AutoSchema",
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework',
    'django_filters.rest_framework.DjangoFilterBackend',    

    #For Search Function
    'rest_framework.filters.SearchFilter'),                

     #For Search Function
    'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework_simplejwt.authentication.JWTAuthentication',],
    # 'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],

    "DATE_INPUT_FORMATS": ["%Y-%m-%d"],
    "DATETIME_FORMAT":"%Y-%m-%d %H:%M:%S",

}

SPECTACULAR_SETTINGS={'title':'Django DRF',}

CORS_ORIGIN_ALLOW_ALL = True  ####ADD

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # Always show the toolbar
}

ROOT_URLCONF = 'autocount_dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'autocount_dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'autocount_dashboard',
#         'USER': 'panda_dev',
#         'PASSWORD': 'Dev@3323966',
#         'HOST': 'localhost',   # Set to the appropriate MySQL host
#         'PORT': '3306',        # Set to the appropriate MySQL port
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'autocount_dashboard', # ubuntu
        'USER': 'panda_dev',
        'PASSWORD': 'Dev@3323966',
        'HOST': '192.168.1.160',   # Set to the appropriate MySQL host
        'PORT': '3306',        # Set to the appropriate MySQL port
    }
    ,
    'windows_server':{
        'ENGINE': 'mssql',
        'NAME': 'AED_VILLY',
        'USER': 'django_dashboard',
        'PASSWORD': 'KKcomputer1234',
        'HOST': '192.168.1.150',
        'PORT': '55913',
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server", 
        }
    },
    'windows_server_book2':{
        'ENGINE': 'mssql',
        'NAME': 'AED_VILLYAGENCY_1',
        'USER': 'django_dashboard',
        'PASSWORD': 'KKcomputer1234',
        'HOST': '192.168.1.150',
        'PORT': '55913',
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server", 
        }
    },
    'windows_server_book3':{
        'ENGINE': 'mssql',
        'NAME': 'AED_VILLY_DOB',
        'USER': 'django_dashboard',
        'PASSWORD': 'KKcomputer1234',
        'HOST': '192.168.1.150',
        'PORT': '55913',
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server", 
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'AED_TEST',
#         'USER': 'admin',
#         'PASSWORD': 'admin',
#         'HOST': '192.168.8.202\A2006',
#         'PORT': '1433',  # Set it to an empty string if not using a specific port
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Use the appropriate ODBC driver version
#         },
#     },
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_TZ = False

USE_L10N = True
LANGUAGES = [
    ('en','English'),
    ('es','Spanish'),
    ('zh-hans',_('Simplified Chinese')),
    ('ml','Malay')
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': False,
#     'BLACKLIST_AFTER_ROTATION': False,
#     'UPDATE_LAST_LOGIN': False,

#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUDIENCE': None,
#     'ISSUER': None,
#     'JWK_URL': None,
#     'LEEWAY': 0,

#     'AUTH_HEADER_TYPES': ('Bearer',),
#     'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
#     'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

#     'JTI_CLAIM': 'jti',

#     'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
#     'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
#     'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
# }

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB